import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const reportPath = path.join(__dirname, '../tests/performance/report.json');
const outputPath = path.join(__dirname, '../tests/performance/report.html');

try {
    const rawData = fs.readFileSync(reportPath);
    const data = JSON.parse(rawData);

    const aggregate = data.aggregate;
    const summaries = aggregate.summaries;
    const counters = aggregate.counters;

    const totalRequests = counters['http.requests'];
    const totalScenarios = counters['vusers.created'];
    const successfulScenarios = counters['vusers.completed'];
    const failedScenarios = counters['vusers.failed'];

    const p95 = summaries['http.response_time'].p95;
    const p99 = summaries['http.response_time'].p99;
    const median = summaries['http.response_time'].median;
    const max = summaries['http.response_time'].max;

    const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Performance Test Report</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 0; background-color: #f4f4f9; color: #333; }
        .container { max-width: 900px; margin: 40px auto; background: #fff; padding: 30px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
        h1 { color: #2c3e50; border-bottom: 2px solid #eee; padding-bottom: 10px; }
        .summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin-top: 20px; }
        .card { background: #f8f9fa; padding: 20px; border-radius: 8px; text-align: center; border: 1px solid #e9ecef; }
        .card h3 { margin: 0; font-size: 14px; color: #6c757d; text-transform: uppercase; }
        .card p { margin: 10px 0 0; font-size: 24px; font-weight: bold; color: #2c3e50; }
        .card.success p { color: #28a745; }
        .card.danger p { color: #dc3545; }
        .metrics-table { width: 100%; border-collapse: collapse; margin-top: 30px; }
        .metrics-table th, .metrics-table td { padding: 12px; text-align: left; border-bottom: 1px solid #eee; }
        .metrics-table th { background-color: #f8f9fa; color: #495057; }
        .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #6c757d; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Performance Test Report</h1>
        <p><strong>Target:</strong> ${data.config ? data.config.target : 'Unknown Target'}</p>
        <p><strong>Date:</strong> ${new Date().toLocaleString()}</p>

        <div class="summary-grid">
            <div class="card">
                <h3>Total Requests</h3>
                <p>${totalRequests}</p>
            </div>
            <div class="card">
                <h3>Scenarios Launched</h3>
                <p>${totalScenarios}</p>
            </div>
            <div class="card success">
                <h3>Successful Scenarios</h3>
                <p>${successfulScenarios}</p>
            </div>
            <div class="card ${failedScenarios > 0 ? 'danger' : ''}">
                <h3>Failed Scenarios</h3>
                <p>${failedScenarios}</p>
            </div>
        </div>

        <h2>Response Time Metrics</h2>
        <table class="metrics-table">
            <thead>
                <tr>
                    <th>Metric</th>
                    <th>Value (ms)</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><strong>Median</strong></td>
                    <td>${median}</td>
                </tr>
                <tr>
                    <td><strong>p95</strong> (95% of requests faster than)</td>
                    <td>${p95}</td>
                </tr>
                <tr>
                    <td><strong>p99</strong> (99% of requests faster than)</td>
                    <td>${p99}</td>
                </tr>
                <tr>
                    <td><strong>Max</strong></td>
                    <td>${max}</td>
                </tr>
            </tbody>
        </table>

        <div class="footer">
            Generated by Custom Artillery Reporter
        </div>
    </div>
</body>
</html>
  `;

    fs.writeFileSync(outputPath, htmlContent);
    console.log('HTML Report generated successfully at:', outputPath);

} catch (error) {
    console.error('Error generating report:', error);
    process.exit(1);
}
